"""Initial auth tables - users and auth_sessions

Revision ID: f5df985ff456
Revises: 
Create Date: 2026-04-04 13:58:32.498001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5df985ff456'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False, comment='会话ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False, comment='加密的 refresh token'),
    sa.Column('access_token', sa.Text(), nullable=True, comment='Access token（可选存储）'),
    sa.Column('id_token', sa.Text(), nullable=True, comment='ID token（可选存储）'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='会话过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('external_auth_id', sa.String(length=255), nullable=False, comment='Keycloak 用户标识 (sub)'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='用户名'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='显示名称'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('given_name', sa.String(length=255), nullable=True, comment='名'),
    sa.Column('family_name', sa.String(length=255), nullable=True, comment='姓'),
    sa.Column('email_verified', sa.Boolean(), nullable=False, comment='邮箱是否验证'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_external_auth_id'), 'users', ['external_auth_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_auth_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
