import logging
import mimetypes
import zipfile
from pathlib import Path, PurePosixPath
from urllib.parse import quote

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import FileResponse, PlainTextResponse, Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.gateway.db.models import User
from app.gateway.db.repository import WorkspaceRepository
from app.gateway.deps import get_current_user, get_db, get_store
from app.gateway.path_utils import resolve_thread_virtual_path
from app.gateway.services.ownership import require_thread_access
from app.gateway.services.workspace_uploads import build_workspace_object_key, ensure_workspace_prefix
from app.gateway.routers.uploads import get_workspace_file_content

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api", tags=["artifacts"])

ACTIVE_CONTENT_MIME_TYPES = {
    "text/html",
    "application/xhtml+xml",
    "image/svg+xml",
}


def _build_content_disposition(disposition_type: str, filename: str) -> str:
    """Build an RFC 5987 encoded Content-Disposition header value."""
    return f"{disposition_type}; filename*=UTF-8''{quote(filename)}"


def _build_attachment_headers(filename: str, extra_headers: dict[str, str] | None = None) -> dict[str, str]:
    headers = {"Content-Disposition": _build_content_disposition("attachment", filename)}
    if extra_headers:
        headers.update(extra_headers)
    return headers


def is_text_file_by_content(path: Path, sample_size: int = 8192) -> bool:
    """Check if file is text by examining content for null bytes."""
    try:
        with open(path, "rb") as file_handle:
            chunk = file_handle.read(sample_size)
            return b"\x00" not in chunk
    except Exception:
        return False


def _extract_file_from_skill_archive(zip_path: Path, internal_path: str) -> bytes | None:
    """Extract a file from a .skill ZIP archive."""
    if not zipfile.is_zipfile(zip_path):
        return None

    try:
        with zipfile.ZipFile(zip_path, "r") as zip_ref:
            namelist = zip_ref.namelist()

            if internal_path in namelist:
                return zip_ref.read(internal_path)

            for name in namelist:
                if name.endswith("/" + internal_path) or name == internal_path:
                    return zip_ref.read(name)

            return None
    except (zipfile.BadZipFile, KeyError):
        return None


def _get_workspace_upload_relative_path(path: str) -> str | None:
    """Return the relative uploads path for workspace-backed thread artifacts."""
    normalized_path = path.lstrip("/")
    uploads_prefix = "mnt/user-data/uploads/"
    if not normalized_path.startswith(uploads_prefix):
        return None

    relative_path = normalized_path.removeprefix(uploads_prefix).strip("/")
    if not relative_path:
        raise HTTPException(status_code=400, detail="Artifact path must include a file name")

    posix_path = PurePosixPath(relative_path)
    if posix_path.is_absolute() or any(part in {"", ".", ".."} for part in posix_path.parts):
        raise HTTPException(status_code=400, detail="Invalid workspace upload path")

    return posix_path.as_posix()


async def _serve_workspace_upload_artifact(
    *,
    workspace_id: str,
    relative_upload_path: str,
    download: bool,
    current_user: User,
    db: AsyncSession,
):
    """Serve a workspace-backed upload through the stable workspace proxy."""
    workspace = await WorkspaceRepository.get_workspace_by_id(db, workspace_id)
    if workspace is None:
        raise HTTPException(status_code=404, detail=f"Workspace {workspace_id} not found")
    if workspace.user_id != current_user.id:
        raise HTTPException(status_code=403, detail=f"Workspace belongs to user {workspace.user_id}")

    root_prefix = await ensure_workspace_prefix(db, workspace)
    object_key = build_workspace_object_key(
        root_prefix,
        relative_upload_path,
        subdir="uploads",
    )
    return await get_workspace_file_content(
        workspace_id=str(workspace.id),
        object_key=object_key,
        download=download,
        current_user=current_user,
        db=db,
    )


@router.get(
    "/threads/{thread_id}/artifacts/{path:path}",
    summary="Get Artifact File",
    description="Retrieve an artifact file generated by the AI agent. Text and binary files can be viewed inline, while active web content is always downloaded.",
)
async def get_artifact(
    thread_id: str,
    path: str,
    request: Request,
    download: bool = False,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Response:
    """Get an artifact file by its path."""
    thread_access = await require_thread_access(
        db=db,
        store=get_store(request),
        thread_id=thread_id,
        current_user=current_user,
    )

    relative_upload_path = _get_workspace_upload_relative_path(path)
    if relative_upload_path is not None and thread_access.thread.workspace_id is not None:
        return await _serve_workspace_upload_artifact(
            workspace_id=str(thread_access.thread.workspace_id),
            relative_upload_path=relative_upload_path,
            download=download,
            current_user=current_user,
            db=db,
        )

    if ".skill/" in path:
        skill_marker = ".skill/"
        marker_pos = path.find(skill_marker)
        skill_file_path = path[: marker_pos + len(".skill")]
        internal_path = path[marker_pos + len(skill_marker) :]

        actual_skill_path = resolve_thread_virtual_path(thread_id, skill_file_path)

        if not actual_skill_path.exists():
            raise HTTPException(status_code=404, detail=f"Skill file not found: {skill_file_path}")

        if not actual_skill_path.is_file():
            raise HTTPException(status_code=400, detail=f"Path is not a file: {skill_file_path}")

        content = _extract_file_from_skill_archive(actual_skill_path, internal_path)
        if content is None:
            raise HTTPException(status_code=404, detail=f"File '{internal_path}' not found in skill archive")

        mime_type, _ = mimetypes.guess_type(internal_path)
        cache_headers = {"Cache-Control": "private, max-age=300"}
        download_name = Path(internal_path).name or actual_skill_path.stem
        if download or mime_type in ACTIVE_CONTENT_MIME_TYPES:
            return Response(
                content=content,
                media_type=mime_type or "application/octet-stream",
                headers=_build_attachment_headers(download_name, cache_headers),
            )

        if mime_type and mime_type.startswith("text/"):
            return PlainTextResponse(content=content.decode("utf-8"), media_type=mime_type, headers=cache_headers)

        try:
            return PlainTextResponse(content=content.decode("utf-8"), media_type="text/plain", headers=cache_headers)
        except UnicodeDecodeError:
            return Response(content=content, media_type=mime_type or "application/octet-stream", headers=cache_headers)

    actual_path = resolve_thread_virtual_path(thread_id, path)

    logger.info("Resolving artifact path: thread_id=%s, requested_path=%s, actual_path=%s", thread_id, path, actual_path)

    if not actual_path.exists():
        raise HTTPException(status_code=404, detail=f"Artifact not found: {path}")

    if not actual_path.is_file():
        raise HTTPException(status_code=400, detail=f"Path is not a file: {path}")

    mime_type, _ = mimetypes.guess_type(actual_path)

    if download:
        return FileResponse(
            path=actual_path,
            filename=actual_path.name,
            media_type=mime_type,
            headers=_build_attachment_headers(actual_path.name),
        )

    if mime_type in ACTIVE_CONTENT_MIME_TYPES:
        return FileResponse(
            path=actual_path,
            filename=actual_path.name,
            media_type=mime_type,
            headers=_build_attachment_headers(actual_path.name),
        )

    if mime_type and mime_type.startswith("text/"):
        return PlainTextResponse(content=actual_path.read_text(encoding="utf-8"), media_type=mime_type)

    if is_text_file_by_content(actual_path):
        return PlainTextResponse(content=actual_path.read_text(encoding="utf-8"), media_type=mime_type)

    return Response(
        content=actual_path.read_bytes(),
        media_type=mime_type,
        headers={"Content-Disposition": _build_content_disposition("inline", actual_path.name)},
    )
